.PHONY: clean

huffman:
	@chmod 755 .
	@python huffman.py

listconcat:
	@chmod 755 .
	@python listconcat.py

levelorder:
	@chmod 755 .
	@python levelorder.py

mergelists:
	@chmod 755 .
	@python mergelists.py

lcrstree:
	@chmod 755 .
	@python lcrstree_test.py

loctree:
	@chmod 755 .
	@python loctreetest.py

pointerqueue:
	@chmod 755 .
	@python pointerqueuetest.py

preorder:
	@chmod 755 .	
	@echo "- * / 15 - 7 + 1 1 3 + 2 + 1 1" |python preorder.py

postorder:
	@chmod 755 .
	@echo "7 8 + 3 2 + /" | python postorder.py

clean:
	@\rm -f *.pyc
